# **PANDAS**

**Importing Pandas**

In [1]:
import pandas as pd

**Understanding Series and DataFrames**

Pandas has two primary data structures:

    Series: A one-dimensional array-like object capable of holding any data type. Think of it as a column in a spreadsheet.

In [2]:
data = pd.Series([1, 3, 5, 7, 9])

DataFrames: A two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns). It’s like a spreadsheet or SQL table.

In [3]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 32],
    'City': ['New York', 'Paris', 'Berlin', 'London']
}
df = pd.DataFrame(data)

**Basic Operations with DataFramesLoading Data**

Pandas makes it easy to load data from various sources like CSV files, Excel spreadsheets, or SQL databases:

df = pd.read_csv('path/to/your/csvfile.csv')

**Viewing Data**

In [4]:
df.head()  # Displays the first 5 rows by default

    Name  Age      City
0   John   28  New York
1   Anna   34     Paris
2  Peter   29    Berlin
3  Linda   32    London

**Accessing Data** Access data in a DataFrame by referencing the column name:

In [5]:
ages = df['Age']  # Access the 'Age' column

In [6]:
print(ages)

0    28
1    34
2    29
3    32
Name: Age, dtype: int64

**Basic Data Manipulation**

Sorting: Sort data by a specific column.

In [7]:
df.sort_values(by='Age')

    Name  Age      City
0   John   28  New York
2  Peter   29    Berlin
3  Linda   32    London
1   Anna   34     Paris

**Filtering: Select rows based on a certain condition.**

In [8]:
df[df['Age'] > 30]  # Selects rows where age is greater than 30

    Name  Age    City
1   Anna   34   Paris
3  Linda   32  London

**Grouping: Group data and perform aggregate functions.**

In [9]:
df.groupby('City')['Age'].mean()  # Groups data by city and calculates mean for each group

City
Berlin      29.0
London      32.0
New York    28.0
Paris       34.0
Name: Age, dtype: float64

**Merging: Combine data from different DataFrame sources.**

In [10]:
#pd.merge(df1, df2, on='common_column')

# 🚀 **Challenge **

We'll simulate a dataset of a small bookstore's sales records. Our dataset will include columns for Book Title, Author, Genre, Price, and Copies Sold.

Here's how you can create this dataset using Pandas:

In [11]:
import pandas as pd

data = {
    'Book Title': ['The Great Gatsby', 'To Kill a Mockingbird', '1984', 'Pride and Prejudice', 'The Catcher in the Rye'],
    'Author': ['F. Scott Fitzgerald', 'Harper Lee', 'George Orwell', 'Jane Austen', 'J.D. Salinger'],
    'Genre': ['Classic', 'Classic', 'Dystopian', 'Classic', 'Classic'],
    'Price': [10.99, 8.99, 7.99, 11.99, 9.99],
    'Copies Sold': [500, 600, 800, 300, 450]
}

df = pd.DataFrame(data)

1. Use head() to view the first few rows of the DataFrame.

In [12]:
print(df.head())

               Book Title               Author      Genre  Price  Copies Sold
0        The Great Gatsby  F. Scott Fitzgerald    Classic  10.99          500
1   To Kill a Mockingbird           Harper Lee    Classic   8.99          600
2                    1984        George Orwell  Dystopian   7.99          800
3     Pride and Prejudice          Jane Austen    Classic  11.99          300
4  The Catcher in the Rye        J.D. Salinger    Classic   9.99          450

2. Use describe() to get a statistical summary of the numerical columns.

In [13]:
print(df.describe())

           Price  Copies Sold
count   5.000000     5.000000
mean    9.990000   530.000000
std     1.581139   185.741756
min     7.990000   300.000000
25%     8.990000   450.000000
50%     9.990000   500.000000
75%    10.990000   600.000000
max    11.990000   800.000000

3. Use info() to get a concise summary of the DataFrame, including the number of non-null entries in each column.

In [15]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Book Title   5 non-null      object
 1   Author       5 non-null      object
 2   Genre        5 non-null      object
 3   Price        5 non-null      float64
 4   Copies Sold  5 non-null      int64
dtypes: float64(1), int64(1), object(3)
memory usage: 332.0+ bytes
None

4. Sort the DataFrame based on the Price or Copies Sold.

In [17]:
print(df.sort_values(by='Copies Sold', ascending=False))

               Book Title               Author      Genre  Price  Copies Sold
2                    1984        George Orwell  Dystopian   7.99          800
1   To Kill a Mockingbird           Harper Lee    Classic   8.99          600
0        The Great Gatsby  F. Scott Fitzgerald    Classic  10.99          500
4  The Catcher in the Rye        J.D. Salinger    Classic   9.99          450
3     Pride and Prejudice          Jane Austen    Classic  11.99          300

In [16]:
print(df.sort_values(by='Price', ascending=False))

               Book Title               Author      Genre  Price  Copies Sold
3     Pride and Prejudice          Jane Austen    Classic  11.99          300
0        The Great Gatsby  F. Scott Fitzgerald    Classic  10.99          500
4  The Catcher in the Rye        J.D. Salinger    Classic   9.99          450
1   To Kill a Mockingbird           Harper Lee    Classic   8.99          600
2                    1984        George Orwell  Dystopian   7.99          800

5. Filter the books by a specific Genre or books with Price above a certain threshold.

In [18]:
print(df[df['Genre'] == 'Classic']) #

               Book Title               Author    Genre  Price  Copies Sold
0        The Great Gatsby  F. Scott Fitzgerald  Classic  10.99          500
1   To Kill a Mockingbird           Harper Lee  Classic   8.99          600
3     Pride and Prejudice          Jane Austen  Classic  11.99          300
4  The Catcher in the Rye        J.D. Salinger  Classic   9.99          450

In [19]:
print(df[df['Price'] > 10])

            Book Title               Author    Genre  Price  Copies Sold
0     The Great Gatsby  F. Scott Fitzgerald  Classic  10.99          500
3  Pride and Prejudice          Jane Austen  Classic  11.99          300

6. Group the books by Author and sum up the Copies Sold.

In [20]:
print(df.groupby('Author')['Copies Sold'].sum())

Author
F. Scott Fitzgerald    500
George Orwell          800
Harper Lee             600
J.D. Salinger          450
Jane Austen            300
Name: Copies Sold, dtype: int64